/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.securepasswordmanager;

/**
 *
 * @author liamf
 */
public class PasswordManagerGUI extends javax.swing.JFrame {
    
    //variables
    private PasswordManager pm;
    private int passwordCount;
    
    public PasswordManagerGUI() {
        initComponents();
        pm = new PasswordManager();//initiliase PasswordManager
        passwordCount = pm.getPasswordCount();//get no. of passwords in DB
        
        //loadAllPasswords();//when started display all saved&encrypted passwords in the DB
        updatePasswordLabel();//this method shows how many passwords have been saved e.g "Saved PAsswords: 3"
    }
    
    private void addPassword(String domain, String plainPassword){
        pm.addPassword(domain,plainPassword);//adds the password to manager
        passwordCount++;
        updatePasswordLabel();//updates the no. of passwords counted
    }
    

    
    private void updatePasswordLabel(){
        SavedPasswordsNumberLBL.setText("SavedPasswords: " + passwordCount);//increment counter every saved pass
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backgrnd = new javax.swing.JPanel();
        TitleLBL = new javax.swing.JLabel();
        SavedPasswordsNumberLBL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayPasswordsTA = new javax.swing.JTextArea();
        AddPasswordBTN = new javax.swing.JButton();
        RetrievePasswordBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Backgrnd.setBackground(new java.awt.Color(204, 255, 255));

        TitleLBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TitleLBL.setText(" Secure Password Manager ");
        TitleLBL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SavedPasswordsNumberLBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SavedPasswordsNumberLBL.setText("Saved Passwords: ");

        DisplayPasswordsTA.setColumns(20);
        DisplayPasswordsTA.setRows(5);
        jScrollPane1.setViewportView(DisplayPasswordsTA);

        AddPasswordBTN.setBackground(new java.awt.Color(153, 255, 153));
        AddPasswordBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddPasswordBTN.setText("Add Password");
        AddPasswordBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPasswordBTNActionPerformed(evt);
            }
        });

        RetrievePasswordBTN.setBackground(new java.awt.Color(255, 153, 153));
        RetrievePasswordBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RetrievePasswordBTN.setText("Retrieve Password");
        RetrievePasswordBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetrievePasswordBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgrndLayout = new javax.swing.GroupLayout(Backgrnd);
        Backgrnd.setLayout(BackgrndLayout);
        BackgrndLayout.setHorizontalGroup(
            BackgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgrndLayout.createSequentialGroup()
                .addGroup(BackgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgrndLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(TitleLBL))
                    .addGroup(BackgrndLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(BackgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddPasswordBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RetrievePasswordBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(BackgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SavedPasswordsNumberLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        BackgrndLayout.setVerticalGroup(
            BackgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgrndLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(TitleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(BackgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgrndLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(SavedPasswordsNumberLBL)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgrndLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(AddPasswordBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(RetrievePasswordBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Backgrnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Backgrnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddPasswordBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPasswordBTNActionPerformed

    }//GEN-LAST:event_AddPasswordBTNActionPerformed

    private void RetrievePasswordBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetrievePasswordBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RetrievePasswordBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasswordManagerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPasswordBTN;
    private javax.swing.JPanel Backgrnd;
    private javax.swing.JTextArea DisplayPasswordsTA;
    private javax.swing.JButton RetrievePasswordBTN;
    private javax.swing.JLabel SavedPasswordsNumberLBL;
    private javax.swing.JLabel TitleLBL;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
